CREATE TABLE [dbo].[weather_data]
(
    [day] DATE NOT NULL, 
    [city] VARCHAR(50) NOT NULL,   
    [lon] FLOAT NULL, 
    [lat] FLOAT NULL,
    [id] INT NULL, 
    [main] VARCHAR(50) NULL, 
    [description] VARCHAR(50) NOT NULL,
    [icon] VARCHAR(50) NULL,  
    [temp] FLOAT NOT NULL, 
    [feels_like] FLOAT NULL, 
    [temp_min] FLOAT NULL, 
    [temp_max] FLOAT NULL, 
    [pressure] INT NULL, 
    [humidity] INT NULL, 
    [wind_speed] FLOAT NULL, 
    [wind_deg] INT NULL, 
    [gust] FLOAT NULL,
    [unit] VARCHAR(20) NOT NULL,
    [sys_type] INT NULL,
    [country] VARCHAR(50) NULL, 
    [sunrise] INT NULL, 
    [sunset] INT NULL,  
    [timezone] INT NULL, 
    CONSTRAINT pk_weather PRIMARY KEY (day, city) 
)